#include "circuit_model.hpp"

namespace aes_xts_decoder {

CircuitModel::CircuitModel(
    std::size_t value_count,
    const std::vector<int32_t>& opcodes,
    const std::vector<int32_t>& outputs,
    const std::vector<int32_t>& input_offsets,
    const std::vector<int32_t>& input_counts,
    const std::vector<int32_t>& inputs,
    const std::vector<int32_t>& immediate_offsets,
    const std::vector<int32_t>& immediate_counts,
    const std::vector<int32_t>& immediates,
    const std::vector<int32_t>& const_offsets,
    const std::vector<int32_t>& const_counts,
    const std::vector<uint8_t>& constants,
    const std::vector<int32_t>& constraint_kinds,
    const std::vector<int32_t>& constraint_left,
    const std::vector<int32_t>& constraint_right,
    const std::vector<int32_t>& wire_value_ids,
    const std::vector<int32_t>& wire_offsets,
    const std::vector<int32_t>& constraint_classes,
    std::size_t plaintext_start,
    std::size_t plaintext_count,
    std::size_t key1_start,
    std::size_t key1_count,
    std::size_t key2_start,
    std::size_t key2_count,
    const std::vector<int32_t>& xts_block_sectors,
    const std::vector<int32_t>& xts_block_indices)
    : value_count(value_count),
      opcodes(opcodes),
      outputs(outputs),
      input_offsets(input_offsets),
      input_counts(input_counts),
      inputs(inputs),
      immediate_offsets(immediate_offsets),
      immediate_counts(immediate_counts),
      immediates(immediates),
      const_offsets(const_offsets),
      const_counts(const_counts),
      constants(constants),
      constraint_kinds(constraint_kinds),
      constraint_left(constraint_left),
      constraint_right(constraint_right),
      wire_value_ids(wire_value_ids),
      wire_offsets(wire_offsets),
      constraint_classes(constraint_classes),
      plaintext_start(plaintext_start),
      plaintext_count(plaintext_count),
      key1_start(key1_start),
      key1_count(key1_count),
      key2_start(key2_start),
      key2_count(key2_count),
      xts_block_sectors(xts_block_sectors),
      xts_block_indices(xts_block_indices) {}

}  // namespace aes_xts_decoder
